# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Devin's Dev Blog
email: dwmois7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcom to Devin's blog site dedicated to all things programming. This page is built with Jekyll 
  and is part of the learning process itself! So enjoy the writings of a developer finding his way
  through a forest of code with posts about experiences, tips, and SWEET MOTHER OF GOD DON'T EVER DO THIS-isms. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Devbot77

# Build settings
markdown: kramdown
